# Generated by Django 3.1.7 on 2021-04-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('about_author', models.TextField()),
                ('slug', models.SlugField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_at', models.DateField(blank=True)),
            ],
        ),
    ]
