# Generated by Django 3.1.7 on 2021-04-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
