# Generated by Django 3.1.7 on 2021-04-01 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='phone',
        ),
    ]
