# Generated by Django 3.1.7 on 2021-04-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookblog', '0006_auto_20210401_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
