# Generated by Django 3.1.7 on 2021-05-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookblog', '0010_loggedinuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
